manifest_version = "1"
id = "wasmcp-typescript"
description = "TypeScript MCP capability provider component"
tags = ["mcp", "http", "typescript", "wasm", "component"]

[parameters]
project-description = { type = "string", prompt = "Description", default = "An MCP server written in TypeScript" }
route = { type = "string", prompt = "HTTP route", default = "/mcp" }

[add_component]
skip_files = ["spin.toml", "README.md", ".gitignore", "package-lock.json", "node_modules"]
[add_component.snippets]
component = "component.txt"