[package]
name = "rust_helpers"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Core dependencies for MCP handler
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wit-bindgen-rt = { version = "0.43.0", features = ["bitflags"] }

# Optional: Add these if you need HTTP or async functionality
# spin-sdk = "4.0"
# spin-executor = "4.0" 
# url = "2.5"

[package.metadata.component]
package = "rust-helpers:handler"

[package.metadata.component.bindings]
derives = ["Clone"]

[package.metadata.component.target]
path = "wit"
world = "tools-handler"

[package.metadata.component.target.dependencies]
"fastertools:mcp" = "0.1.1"

[profile.release]
# Optimize for small binary size
opt-level = "s"
lto = true
strip = true