[package]
name = "wasmcp-spin-async"
version = "0.1.0"
edition = "2021"

[dependencies]
spin-sdk = "3.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
tokio = { version = "1", features = ["sync"] }
base64 = "0.22"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "wasmcp:spin"

[package.metadata.component.dependencies]
"wasmcp:mcp" = { path = "../../../tmp/test-wasmcp-wasi-typescript/handler/wit" }