# Wasmtime configuration for running MCP server with authorization

[[wasi.config]]
# JWT Configuration
"jwt.expected_issuer" = "https://your-auth.auth0.com/"
"jwt.expected_audience" = "https://your-mcp-api" 
"jwt.jwks_uri" = "https://your-auth.auth0.com/.well-known/jwks.json"
"jwt.validation_leeway" = "60"

# OAuth Discovery Configuration  
"oauth.resource_url" = "https://your-mcp-server.com"
"oauth.auth_server" = "https://your-auth.auth0.com"
"oauth.auth_issuer" = "https://your-auth.auth0.com/"
"oauth.auth_endpoint" = "https://your-auth.auth0.com/authorize"
"oauth.token_endpoint" = "https://your-auth.auth0.com/oauth/token"
"oauth.registration_endpoint" = "https://your-auth.auth0.com/oauth/register"

# Policy Configuration
"policy.mode" = "default"  # Options: "default", "rbac", "custom", "none"
# "policy.path" = "/path/to/custom.rego"  # For custom policies