[package]
name = "wasmcp_spin"
version = "0.0.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
spin-sdk = "3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
base64 = "0.22"
wit-bindgen-rt = { version = "0.43.0", features = ["bitflags"] }

[package.metadata.component]
package = "wasmcp:spin"

[package.metadata.component.target]
path = "wit"
world = "mcp-spin-api"

[package.metadata.component.target.dependencies]
"wasmcp:mcp" = { path = "../../../wit" }

[workspace]