manifest_version = "1"
id = "wasmcp-go"
description = "MCP server using Go"
tags = ["go", "mcp", "http"]

[parameters]
project-name = { description = "Project name", pattern = "^[a-zA-Z][a-zA-Z0-9_-]*$" }
authors = { description = "Authors", default = "Your Name" }