manifest_version = "1"
id = "wasmcp-go"
description = "Go wasmcp handler component"
tags = ["go", "mcp", "http", "wasm", "component"]

[parameters]
project-description = { type = "string", prompt = "Description", default = "An MCP server written in Go" }
route = { type = "string", prompt = "HTTP route", default = "/mcp" }

[add_component]
skip_files = ["spin.toml", "README.md", ".gitignore"]
[add_component.snippets]
component = "component.txt"