manifest_version = "1"
id = "wasmcp-go"
description = "Go MCP capability provider component"
tags = ["mcp", "http", "go", "tinygo", "wasm", "component"]

[parameters]
project-description = { type = "string", prompt = "Description", default = "An MCP server written in Go" }
route = { type = "string", prompt = "HTTP route", default = "/mcp" }

[add_component]
skip_files = ["spin.toml", "README.md", ".gitignore", "go.mod", "go.sum"]
[add_component.snippets]
component = "component.txt"