spin_manifest_version = 2

[application]
name = "typescript-weather"
version = "0.1.0"
authors = ["Ian McDonald <bowlofarugula@gmail.com>"]
description = "An MCP server written in TypeScript"

[[trigger.http]]
route = "/mcp"
component = "wasmcp-spin"

[component.wasmcp-spin]
# Using the pre-composed component
source = "composed.wasm"
# Allow outbound HTTP requests for weather API
allowed_outbound_hosts = ["https://geocoding-api.open-meteo.com", "https://api.open-meteo.com"]