# Rust 2024 edition formatting
edition = "2024"

# Strict formatting rules
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Imports
imports_indent = "Block"
imports_layout = "Vertical"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Code style
format_code_in_doc_comments = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true

# Consistency
use_field_init_shorthand = true
use_try_shorthand = true
match_block_trailing_comma = true
trailing_semicolon = true
trailing_comma = "Vertical"

# Space and alignment
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
match_arm_blocks = true
force_explicit_abi = true