[package]
name = "{{project-name | snake_case}}"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmcp = "0.1.6"
wit-bindgen-rt = "0.44.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
spin-sdk = "4.0.0"

[dev-dependencies]
serde_json = { version = "1.0", features = ["preserve_order"] }
tokio = { version = "1.0", features = ["rt", "time", "macros"] }
futures = "0.3"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "{{project-name | kebab_case}}:handler"

[package.metadata.component.target]
path = "wit"
world = "mcp-handler"

[package.metadata.component.target.dependencies]
"wasi:http" = { path = "wit/deps/wasi-http-0.2.0" }
"wasi:io" = { path = "wit/deps/wasi-io-0.2.0" }
"wasi:clocks" = { path = "wit/deps/wasi-clocks-0.2.0" }
"wasi:random" = { path = "wit/deps/wasi-random-0.2.0" }

[profile.release]
# Optimize for small binary size
opt-level = "s"
lto = true
strip = true