spin_manifest_version = 2

[application]
name = "rust-no-wit"
version = "0.1.0"
authors = ["Ian McDonald <bowlofarugula@gmail.com>"]
description = "An MCP server written in Rust"

[[trigger.http]]
route = "/mcp"
component = "wasmcp-spin"

[component.wasmcp-spin]
# Using the local gateway component
source = "wasmcp-spin.wasm"
allowed_outbound_hosts = [
    "https://geocoding-api.open-meteo.com",
    "https://api.open-meteo.com"
]
dependencies_inherit_configuration = true
key_value_stores = ["default"]

[component.wasmcp-spin.dependencies]
# Link to the local handler component
"wasmcp:mcp/handler@0.1.0" = { path = "./handler/target/wasm32-wasip1/release/rust_no_wit.wasm" }

[component.wasmcp-spin.build]
command = "make build"
watch = ["handler/src/**/*.rs", "handler/Cargo.toml", "handler/wit/*.wit"]