spin_manifest_version = 2

[application]
name = "{{project-name | kebab_case}}"
version = "0.1.0"
authors = ["{{authors}}"]
description = "{{project-description}}"

[[trigger.http]]
route = "{{route}}"
component = "composed"

[component.composed]
# Using the composed component (handler + server)
source = "composed.wasm"
# Weather API hosts for example tools (remove if not needed)
allowed_outbound_hosts = [
    "https://geocoding-api.open-meteo.com",
    "https://api.open-meteo.com"
]
key_value_stores = ["default"]

[component.composed.build]
command = "make build"
watch = ["*.js", "package.json", "wit/*.wit"]