[package]
name = "mcp_transport_http"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
spin-sdk = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
base64 = "0.22"
wit-bindgen-rt = { version = "0.43.0", features = ["bitflags"] }
rmcp = { version = "0.5", default-features = false, features = ["server", "macros", "base64"] }

[features]
default = ["tools", "auth"]

# Capabilities - choose which capabilities this transport will support
tools = []
resources = []
prompts = []
sampling = []
elicitation = []
roots = []
completion = []

# Common combinations
basic = ["tools", "resources"]
standard = ["tools", "resources", "prompts"]
full = ["tools", "resources", "prompts", "sampling", "elicitation", "roots", "completion"]

# Transport features
sse = []  # Server-Sent Events for subscriptions and notifications
auth = []  # OAuth 2.0 authorization support

# State management (future)
# sessions = ["dep:wasi-keyvalue"]  # Stateful session support

[package.metadata.component]
package = "mcp:transport-http"

[package.metadata.component.bindings]
derives = ["serde::Serialize", "serde::Deserialize", "Clone"]

[package.metadata.component.target]
package = "fastertools:mcp"
version = "0.1.12"
# Note: Choose world based on features when building:
# - tools only: tools-transport
# - tools + auth: tools-auth-transport
# - tools + resources + auth: tools-resources-auth-transport
# - all features + auth: full-auth-transport
world = "tools-auth-transport" # Use tools transport with auth 

[workspace]