spin_manifest_version = 2

[application]
name = "mcp-demo-authkit"
version = "0.1.0"
description = "MCP server with AuthKit authentication"

[[trigger.http]]
route = "/..."
component = "mcp-server"

[component.mcp-server]
source = "../../src/components/wasmcp-spin-authkit/target/wasm32-wasip1/release/wasmcp_spin_authkit.wasm"
allowed_outbound_hosts = ["https://*"]  # For JWKS fetching

[component.mcp-server.variables]
# Replace with your AuthKit configuration
authkit_issuer = "https://divine-lion-50-staging.authkit.app"
authkit_jwks_uri = "https://divine-lion-50-staging.authkit.app/oauth2/jwks"
# authkit_audience = "your-audience"  # Optional

[component.mcp-server.dependencies]
# Link to your MCP handler
"wasmcp:mcp/handler" = { path = "./handler/target/wasm32-wasip1/release/auth_demo_handler.wasm" }