spin_manifest_version = 2

[application]
name = "python-echo"
version = "0.1.0"
authors = ["wasmcp contributors"]
description = "An MCP server written in Python with echo and weather tools"

[[trigger.http]]
route = "/mcp"
component = "wasmcp-spin"

[component.wasmcp-spin]
# Using the local gateway component
source = "wasmcp-server.wasm"
allowed_outbound_hosts = [
    # Weather API
    "https://wttr.in"
]
dependencies_inherit_configuration = true
key_value_stores = ["default"]

[component.wasmcp-spin.dependencies]
# Link to the local handler component
"wasmcp:mcp/handler@0.1.0" = { path = "minimal.wasm" }

[component.wasmcp-spin.build]
command = "./build_minimal.sh"
watch = ["handler/src/**/*.py", "handler/requirements.txt", "handler/componentize-py.toml"]