spin_manifest_version = 2

[application]
name = "python-echo"
version = "0.1.0"
authors = ["wasmcp contributors"]
description = "An MCP server written in Python with echo and weather tools"

[[trigger.http]]
route = "/mcp"
component = "wasmcp-spin"

[component.wasmcp-spin]
# Using the local gateway component
source = "wasmcp-server.wasm"
allowed_outbound_hosts = [
    # Add external hosts here if implementing real weather API
    # "https://api.openweathermap.org",
    # "https://geocoding-api.open-meteo.com"
]
dependencies_inherit_configuration = true
key_value_stores = ["default"]

[component.wasmcp-spin.dependencies]
# Link to the local handler component
"wasmcp:mcp/handler@0.1.0" = { path = "./handler/app.wasm" }

[component.wasmcp-spin.build]
command = "make build"
watch = ["handler/src/**/*.py", "handler/requirements.txt", "handler/componentize-py.toml"]