[package]
name = "wasmcp"
version = "0.1.3"
edition = "2021"
description = "Rust SDK for building MCP (Model Context Protocol) WebAssembly components"
license = "Apache-2.0"
repository = "https://github.com/fastertools/wasmcp"
keywords = ["mcp", "wasm", "webassembly", "components"]
categories = ["wasm", "web-programming", "api-bindings"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["rt", "rt-multi-thread"] }

[dev-dependencies]