[package]
name = "wasmcp"
version = "0.2.7"
edition = "2021"
description = "Rust SDK for building MCP (Model Context Protocol) WebAssembly components"
license = "Apache-2.0"
repository = "https://github.com/fastertools/wasmcp"
keywords = ["mcp", "wasm", "webassembly", "components"]
categories = ["wasm", "web-programming", "api-bindings"]
include = ["src/**/*", "Cargo.toml", "README.md"]

[dependencies]
wasmcp-macro = "0.1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
spin-executor = "4.0"
wit-bindgen = "0.43.0"

[dev-dependencies]