[package]
name = "rust_weather"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
spin-sdk = "4.0"
spin-executor = "4.0"
url = "2.5"
wit-bindgen-rt = { version = "0.43.0", features = ["bitflags"] }

[package.metadata.component]
package = "example:weather"

[package.metadata.component.bindings]
derives = ["serde::Serialize", "serde::Deserialize", "Clone"]

[package.metadata.component.target]
path = "wit"
world = "mcp-server"

[package.metadata.component.target.dependencies]
"fastertools:mcp" = "0.1.0"

[profile.release]
# Optimize for small binary size
opt-level = "s"
lto = true
strip = true