manifest_version = "1"
id = "wasmcp-rust"
description = "Rust wasmcp handler component"
tags = ["mcp", "http", "rust", "wasm", "component"]

[parameters]
project-description = { type = "string", prompt = "Description", default = "An MCP tool written in Rust" }
route = { type = "string", prompt = "HTTP route", default = "/mcp" }

[add_component]
skip_files = ["spin.toml", "README.md", ".gitignore"]
[add_component.snippets]
component = "component.txt"