[package]
name = "wasmcp-wasi"
version = "0.1.0"
edition = "2021"
description = "Minimal WASI SDK for MCP handlers - provides HTTP, KV, and Config"
license = "Apache-2.0"
repository = "https://github.com/fastertools/wasmcp"

[dependencies]
wit-bindgen = "0.43.0"
# Pin to the last version that targeted WASI 0.2.0
wasi = "=0.13.1"
futures = "0.3.28"
bytes = "1"
http = "1.0.0"
url = "2.5"
anyhow = "1"
async-trait = "0.1.74"

# Re-export spin-executor for blocking on async
spin-executor = "4.0.0"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt"] }
