# Azure AD / Microsoft Entra ID Configuration Example
# Replace YOUR_TENANT_ID with your Azure tenant ID
# Replace YOUR_CLIENT_ID with your application (client) ID

[[wasi.config]]
# JWT Configuration for Azure AD
"jwt.expected_issuer" = "https://login.microsoftonline.com/YOUR_TENANT_ID/v2.0"
"jwt.expected_audience" = "api://YOUR_CLIENT_ID"  # or your Application ID URI
"jwt.jwks_uri" = "https://login.microsoftonline.com/YOUR_TENANT_ID/discovery/v2.0/keys"
"jwt.validation_leeway" = "60"

# OAuth Discovery Configuration
"oauth.resource_url" = "https://your-mcp-server.com"
"oauth.auth_server" = "https://login.microsoftonline.com/YOUR_TENANT_ID/v2.0"
"oauth.auth_issuer" = "https://login.microsoftonline.com/YOUR_TENANT_ID/v2.0"
"oauth.auth_endpoint" = "https://login.microsoftonline.com/YOUR_TENANT_ID/oauth2/v2.0/authorize"
"oauth.token_endpoint" = "https://login.microsoftonline.com/YOUR_TENANT_ID/oauth2/v2.0/token"
"oauth.registration_endpoint" = ""  # Azure AD doesn't support dynamic registration

# Policy Configuration
"policy.mode" = "rbac"  # Azure AD supports app roles and groups