# Google OAuth Configuration Example
# For Google Sign-In / Google Identity Platform

[[wasi.config]]
# JWT Configuration for Google
"jwt.expected_issuer" = "https://accounts.google.com"
"jwt.expected_audience" = "YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com"
"jwt.jwks_uri" = "https://www.googleapis.com/oauth2/v3/certs"
"jwt.validation_leeway" = "60"

# OAuth Discovery Configuration
"oauth.resource_url" = "https://your-mcp-server.com"
"oauth.auth_server" = "https://accounts.google.com"
"oauth.auth_issuer" = "https://accounts.google.com"
"oauth.auth_endpoint" = "https://accounts.google.com/o/oauth2/v2/auth"
"oauth.token_endpoint" = "https://oauth2.googleapis.com/token"
"oauth.registration_endpoint" = ""  # Google doesn't support dynamic registration

# Policy Configuration
"policy.mode" = "default"