spin_manifest_version = 2

[application]
name = "typescript-weather"
version = "0.1.0"
authors = ["Ian McDonald <bowlofarugula@gmail.com>"]
description = "An MCP server written in TypeScript"

[[trigger.http]]
route = "/mcp"
component = "wasmcp-server"

[component.wasmcp-server]
# Using the local server component
source = "wasmcp-server.wasm"
build.command = "make build"
build.watch = ["handler/src/**/*.ts", "handler/package.json", "handler/tsconfig.json"]
# Allow outbound HTTP requests for weather API
allowed_outbound_hosts = ["https://geocoding-api.open-meteo.com", "https://api.open-meteo.com"]

[component.wasmcp-server.dependencies]
# Link to the local handler component
"wasmcp:mcp/handler" = { path = "./handler/dist/handler.wasm" }