[package]
name = "{{project-name | snake_case}}"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Core dependencies for MCP provider
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wit-bindgen-rt = { version = "0.43.0", features = ["bitflags"] }

# For async HTTP requests
spin-sdk = "4.0"
futures = "0.3"
urlencoding = "2.1"
lazy_static = "1.5"

[package.metadata.component]
package = "{{project-name | kebab_case}}:provider"

[package.metadata.component.bindings]
derives = ["Clone"]

[package.metadata.component.target]
package = "fastertools:mcp"
version = "0.1.23"
world = "tools-provider"

[profile.release]
# Optimize for small binary size
opt-level = "s"
lto = true
strip = true

[lints.rust]
# Rustc lints
missing_docs = "warn"
rust_2024_compatibility = "warn"

[lints.clippy]
# Pedantic lints
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"

# Restriction lints
unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
unimplemented = "warn"
todo = "warn"

# Correctness
correctness = "deny"

# Performance
perf = "warn"

# Style
needless_pass_by_value = "warn"
redundant_closure_for_method_calls = "warn"
inconsistent_struct_constructor = "warn"