# Rust 2024 edition formatting
edition = "2024"

# Strict formatting rules
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Imports
# imports_indent = "Block"  # nightly only
# imports_layout = "Vertical"  # nightly only
# group_imports = "StdExternalCrate"  # nightly only
reorder_imports = true
reorder_modules = true

# Code style
# format_code_in_doc_comments = true  # nightly only
# format_strings = true  # nightly only
# format_macro_matchers = true  # nightly only
# format_macro_bodies = true  # nightly only
# normalize_comments = true  # nightly only
# normalize_doc_attributes = true  # nightly only
# wrap_comments = true  # nightly only

# Consistency
use_field_init_shorthand = true
use_try_shorthand = true
match_block_trailing_comma = true
# trailing_semicolon = true  # nightly only
# trailing_comma = "Vertical"  # nightly only

# Space and alignment
# space_before_colon = false  # nightly only
# space_after_colon = true  # nightly only
# spaces_around_ranges = false  # nightly only
# match_arm_blocks = true  # nightly only
force_explicit_abi = true