spin_manifest_version = 2

[application]
name = "{{project-name | kebab_case}}"
version = "0.1.0"
authors = ["{{authors}}"]
description = "{{project-description}}"

[[trigger.http]]
route = "/mcp"
component = "composed"

[component.composed]
# Using the composed component (handler + null components + server)
source = "composed.wasm"
allowed_outbound_hosts = [
    "https://geocoding-api.open-meteo.com",
    "https://api.open-meteo.com"
]
key_value_stores = ["default"]

[component.composed.build]
command = "make build"
watch = ["src/**/*.rs", "Cargo.toml", "wit/*.wit"]