spin_manifest_version = 2

[application]
name = "{{project-name | kebab_case}}"
version = "0.1.0"
authors = ["{{authors}}"]
description = "{{project-description}}"

[[trigger.http]]
route = "/mcp"
component = "wasmcp-spin"

[component.wasmcp-spin]
# Using the published gateway component
source = { registry = "ghcr.io", package = "fastertools:wasmcp-spin", version = "0.0.3" }
allowed_outbound_hosts = [
    "https://geocoding-api.open-meteo.com",
    "https://api.open-meteo.com"
]
dependencies_inherit_configuration = true
key_value_stores = ["default"]

[component.wasmcp-spin.dependencies]
# Link to the local handler component
"wasmcp:mcp/handler@0.1.0" = { path = "./handler/target/wasm32-wasip1/release/{{project-name | snake_case}}.wasm" }

[component.wasmcp-spin.build]
command = "make build"
watch = ["handler/src/**/*.rs", "handler/Cargo.toml", "handler/wit/*.wit"]