[package]
name = "wasmcp-macros"
version = "0.2.0"
edition = "2021"
description = "Procedural macros for the wasmcp SDK"
license = "Apache-2.0"
repository = "https://github.com/fastertools/wasmcp"
keywords = ["mcp", "wasm", "webassembly", "macros"]
categories = ["wasm", "web-programming"]
include = ["src/**/*", "Cargo.toml"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
serde_json = "1.0"