[package]
name = "wasmcp"
version = "0.3.0"
edition = "2021"
description = "Rust SDK for building MCP (Model Context Protocol) WebAssembly components"
license = "Apache-2.0"
repository = "https://github.com/fastertools/wasmcp"
keywords = ["mcp", "wasm", "webassembly", "components", "wit"]
categories = ["wasm", "web-programming", "api-bindings"]
include = ["src/**/*", "wit/**/*", "Cargo.toml", "README.md"]

[lib]
crate-type = ["lib"]

[dependencies]
wasmcp-macros = { path = "../rust-macros", version = "0.2.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wit-bindgen = { version = "0.43.0", features = ["realloc"] }
spin-executor = "4.0"

[dev-dependencies]

