name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-rust:
    name: Build Rust Components
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-wasip1
    
    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@main
    
    - name: Install cargo-component
      run: cargo binstall cargo-component --no-confirm
    
    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build mcp-http-component
      working-directory: src/mcp-http-component
      run: |
        cargo component build --release
        cargo test
    
    - name: Build ftl-sdk-rust
      working-directory: src/ftl-sdk-rust
      run: |
        cargo build --release
        cargo test
    
    - name: Upload mcp-http-component artifact
      uses: actions/upload-artifact@v4
      with:
        name: mcp-http-component
        path: src/mcp-http-component/target/wasm32-wasip1/release/mcp_http_component.wasm

  build-typescript:
    name: Build TypeScript SDK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: src/ftl-sdk-typescript/package-lock.json
    
    - name: Install dependencies
      working-directory: src/ftl-sdk-typescript
      run: npm ci
    
    - name: Build
      working-directory: src/ftl-sdk-typescript
      run: npm run build
    
    - name: Test
      working-directory: src/ftl-sdk-typescript
      run: npm test || echo "No tests configured"