name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  validate-versions:
    name: Validate Version Consistency
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check version consistency
      run: make validate-versions
    
    - name: Check WIT file consistency
      run: make validate-wit

  build-and-test:
    name: Build and Test All Components
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-wasip1
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: src/sdk/wasmcp-typescript/package-lock.json
    
    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@main
    
    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Run CI pipeline
      run: make ci
    
    - name: Upload wasmcp-server artifact
      uses: actions/upload-artifact@v4
      with:
        name: wasmcp-server
        path: src/components/wasmcp-server/target/wasm32-wasip1/release/wasmcp_server.wasm